export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_PARCEL_ORDER = 'LOAD_PARCEL_ORDER';
export const CREATE_PARCEL = 'CREATE_PARCEL';
export const CURRENT_PARCEL_ORDER = 'CURRENT_PARCEL_ORDER';
